from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Border,
    Side,
    Alignment
)

from utils.datetime_helper import (
    format_jakarta_datetime,
    get_jakarta_now
)


def create_monthly_report_excel(
    bakery_name: str,
    period: str,
    generated_by: str,
    sales: list,
    summary: dict,
    payments: dict,
    top_products: list,
    production_history: list,
    stock_movements: list
):

    wb = Workbook()

    # =====================================
    # STYLES
    # =====================================

    title_font = Font(
        bold=True,
        size=18
    )

    subtitle_font = Font(
        bold=True,
        size=13
    )

    bold_font = Font(
        bold=True
    )

    white_font = Font(
        bold=True,
        color="FFFFFF"
    )

    blue_fill = PatternFill(
        fill_type="solid",
        fgColor="1F4E78"
    )

    thin = Side(style="thin")

    border = Border(
        left=thin,
        right=thin,
        top=thin,
        bottom=thin
    )

    center = Alignment(
        horizontal="center",
        vertical="center"
    )

    currency = '"Rp"#,##0'

    # =====================================
    # SUMMARY
    # =====================================

    ws = wb.active

    ws.title = "Summary"

    ws["A1"] = bakery_name
    ws["A1"].font = title_font

    ws["A2"] = "MONTHLY SALES REPORT"
    ws["A2"].font = subtitle_font

    ws.append([])

    ws.append([
        "Generated",
        get_jakarta_now().strftime(
            "%d %b %Y %H:%M WIB"
        )
    ])

    ws.append([
        "Generated By",
        generated_by
    ])

    ws.append([
        "Period",
        period
    ])

    ws.append([])

    ws.append([
        "Revenue",
        summary["revenue"]
    ])

    ws.append([
        "Transactions",
        summary["transactions"]
    ])

    ws["A8"].font = bold_font
    ws["A9"].font = bold_font

    ws["B8"].number_format = currency

    # =====================================
    # TRANSACTIONS
    # =====================================

    tx = wb.create_sheet(
        "Transactions"
    )

    headers = [
        "No",
        "Timestamp (WIB)",
        "Cashier",
        "Payment",
        "Total",
        "Items"
    ]

    tx.append(headers)

    for cell in tx[1]:

        cell.font = white_font
        cell.fill = blue_fill
        cell.border = border
        cell.alignment = center

    row_no = 1

    for sale in sales:

        items = []

        for item in sale["sales_items"]:

            items.append(
                f"{item['products']['name']} x{item['quantity']}"
            )

        tx.append([
            row_no,
            format_jakarta_datetime(
                sale["created_at"]
            ),
            sale["cashier_name"],
            sale["payment_method"],
            sale["total_amount"],
            ", ".join(items)
        ])

        current_row = tx.max_row

        tx[f"E{current_row}"].number_format = currency

        for cell in tx[current_row]:

            cell.border = border

        row_no += 1

    tx.append([])

    tx.append([
        "",
        "",
        "",
        "TOTAL",
        summary["revenue"],
        ""
    ])

    total_row = tx.max_row

    tx[f"D{total_row}"].font = bold_font
    tx[f"E{total_row}"].font = bold_font
    tx[f"E{total_row}"].number_format = currency
    
    # =====================================
    # PAYMENT BREAKDOWN
    # =====================================

    payment_ws = wb.create_sheet(
        "Payments"
    )

    payment_ws.append([
        "Payment Method",
        "Amount"
    ])

    for cell in payment_ws[1]:

        cell.font = white_font
        cell.fill = blue_fill
        cell.border = border
        cell.alignment = center

    for method, amount in payments.items():

        payment_ws.append([
            method,
            amount
        ])

        row = payment_ws.max_row

        payment_ws[f"B{row}"].number_format = currency

        for cell in payment_ws[row]:

            cell.border = border

    payment_ws.append([])

    payment_ws.append([
        "TOTAL",
        summary["revenue"]
    ])

    total_payment_row = payment_ws.max_row

    payment_ws[f"A{total_payment_row}"].font = bold_font
    payment_ws[f"B{total_payment_row}"].font = bold_font
    payment_ws[f"B{total_payment_row}"].number_format = currency

    # =====================================
    # TOP PRODUCTS
    # =====================================

    product_ws = wb.create_sheet(
        "Top Products"
    )

    product_ws.append([
        "Rank",
        "Product",
        "Quantity Sold"
    ])

    for cell in product_ws[1]:

        cell.font = white_font
        cell.fill = blue_fill
        cell.border = border
        cell.alignment = center

    rank = 1

    for product, quantity in top_products:

        product_ws.append([
            rank,
            product,
            quantity
        ])

        row = product_ws.max_row

        for cell in product_ws[row]:

            cell.border = border

        rank += 1
        
    # =====================================
    # PRODUCTION HISTORY
    # =====================================

    production_ws = wb.create_sheet(
        "Production History"
    )

    production_ws.append([
        "No",
        "Timestamp",
        "Product",
        "Quantity Produced"
        "Staff"
    ])

    for cell in production_ws[1]:

        cell.font = white_font
        cell.fill = blue_fill
        cell.border = border
        cell.alignment = center

    no = 1

    for production in production_history:

        production_ws.append([
            no,
            format_jakarta_datetime(
                production["created_at"]
            ),
            production["products"]["name"],
            production["quantity_added"],
            production["staff_name"]
        ])

        row = production_ws.max_row

        for cell in production_ws[row]:

            cell.border = border

        no += 1
        
    # =====================================
    # STOCK MOVEMENTS
    # =====================================

    movement_ws = wb.create_sheet(
        "Stock Movements"
    )

    movement_ws.append([
        "No",
        "Timestamp",
        "Product",
        "Action",
        "Quantity",
        "Before Stock",
        "After Stock",
        "Staff",
        "Notes"
])

    for cell in movement_ws[1]:

        cell.font = white_font
        cell.fill = blue_fill
        cell.border = border
        cell.alignment = center

    no = 1

    for movement in stock_movements:

        qty = movement["quantity"]

        if movement["action"] == "SALE":

            qty = -qty

        elif movement["action"] == "PRODUCTION":

            qty = f"+{qty}"

        movement_ws.append([
            no,
            format_jakarta_datetime(
                movement["created_at"]
            ),
            movement["products"]["name"],
            movement["action"],
            qty,
            movement["before_stock"],
            movement["after_stock"],
            movement["staff_name"],
            movement["notes"]
        ])

        row = movement_ws.max_row

        for cell in movement_ws[row]:

            cell.border = border

        no += 1

    # =====================================
    # AUTO WIDTH
    # =====================================

    for sheet in wb.worksheets:

        for column_cells in sheet.columns:

            max_length = 0

            column = column_cells[0].column_letter

            for cell in column_cells:

                try:

                    if cell.value:

                        max_length = max(
                            max_length,
                            len(str(cell.value))
                        )

                except Exception:

                    pass

            sheet.column_dimensions[
                column
            ].width = max_length + 4

    # =====================================
    # FREEZE PANES
    # =====================================

    ws.freeze_panes = "A4"

    tx.freeze_panes = "A2"

    payment_ws.freeze_panes = "A2"

    product_ws.freeze_panes = "A2"
    
    production_ws.freeze_panes = "A2"
    
    movement_ws.freeze_panes = "A2"

    # =====================================
    # AUTO FILTERS
    # =====================================

    tx.auto_filter.ref = tx.dimensions

    payment_ws.auto_filter.ref = (
        payment_ws.dimensions
    )

    product_ws.auto_filter.ref = (
        product_ws.dimensions
    )

    production_ws.auto_filter.ref = (
        production_ws.dimensions
    )
    
    movement_ws.auto_filter.ref = (
        movement_ws.dimensions
    )
    
    # =====================================
    # ALIGN SUMMARY
    # =====================================

    for row in range(4, 10):

        ws[f"A{row}"].font = bold_font

    # =====================================
    # DONE
    # =====================================

    return wb